export const FETCH_USERS_REQUEST="FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED="FETCH_USERS_FAILED";

export const SINGLE_USER_REQUEST="SINGLE_USER_REQUEST";
export const SINGLE_USER_SUCCESS="SINGLE_USER_SUCCESS";
export const SINGLE_USER_FAILED="SINGLE_USER_FAILED";